export default Select;
declare class Select {
    static createSafeCssClassname(str: any): string;
    static moveFocusToSelectTrigger(target: any): void;
    static trapFocus(element: any): void;
    static moveFocus(element: any): void;
    static toggleClass(el: any, className: any, bool: any): void;
    constructor(element: any);
    element: any;
    select: any;
    options: any;
    optGroups: any;
    selectId: any;
    trigger: boolean;
    dropdown: boolean;
    customOptions: boolean;
    optionIndex: number;
    textSelected: any;
    init(): void;
    initCustomSelect(): void;
    multiSelectList: any;
    allButton: any;
    allButtonInput: any;
    initCustomSelectEvents(): void;
    toggleCustomSelect(bool: any): void;
    placeDropdown(): void;
    keyboardCustomSelect(direction: any, event: any): void;
    initSelection(): void;
    getSelectedOptionCount(): number;
    toggleAllOptions(): void;
    selectOption(option: any): void;
    initButtonSelect(): string;
    initAllButton(): string;
    getSelectedOptionText(): string[];
    initListSelect(): string;
    getOptionsList(options: any): string;
    getSelectedOption(): any;
    checkCustomSelectClick(target: any): void;
    updateNativeSelect(index: any, bool: any): void;
    updateTriggerAria(ariaLabel: any): void;
}
